### PR TITLE
fix missing dependency for url

### PR DESCRIPTION
**Pull request by smeng9**
Closes https://github.com/tdegrunt/jsonschema/issues/367

@tdegrunt can you help take a look and release a new version?

### CODE REVIEW

**Comment by smeng9** [comment]
Hi @tdegrunt any updates on this? We will need the url dependency in order to properly use this package.

**Comment by smeng9** [comment]
Hi @awwright,

I am using yarn pnp as package manager with vite to build my projects. It gives the following error Module “url” has been externalized for browser compatibility. 

Someone else also posted on the original issue on how to reproduce this problem. https://github.com/tdegrunt/jsonschema/issues/367#issuecomment-1543822066

**Comment by smeng9** [comment]
Hi @awwright, Any updates on this? The url package is not built-in and we need to fix the dependencies in order to use it.

**Comment by awwright** [comment]
@smeng9 We only claim to support Node.js where `url` ought to be built-in; and any tools that adapt the code for other environments must support Node.js compatibility. You should file an issue upstream with your package manager, and link it here.

**Pull request closed without merging**
