### PR TITLE
BugFixes: (instanceof Array/Object/RegExp) and (undefined property handling)

### PR DESCRIPTION
**Pull request by pdunkel**
Hi,

These are 2 Bug-Fix Commits:

The first eliminated the use of the instanceof operator. This is due to the fact that when the origin of your JSON-Object is from another frame/window in a browser, or another execution-context in node, that operator breaks.

The second makes sure that properties whose value is undefined are handled properly. Since JSON does not have an undefined value, they should be treated as not present.

### CODE REVIEW

**Comment by pdunkel** [comment]
As mentioned in #70:


The reason why instanceof is a bad idea, is because you do not know the origin of your JSON. If it comes from another execution-context (possible in node/v8) which in a browser would be another frame/window, then instanceof will cease to work.

The reason for this is that instanceof checks the prototype chain of the left-hand operand for identity-equality (===) with the right-hand operand. If along that chain it finds the right-hand operand it resolves to true otherwise to false. The problem arises due to the fact that across execution-contexts the built-in Objects (Array, Object, RegExp, Date, ...) are different. Each execution-context has their own. Due to this strict-equality will never be true.

The consequence of this is that the fix I put in (for Array, Object, Date and RegExp) will not have negative side-effects.

**Comment by Acubed** [comment]
I'll have to take a closer look at this, since this seems like a decent use case, but in some cases what you're calling "bad" for me is actually the desired behavior, I'm looking for objects to be an instance of a specific prototype, for instance, a MongoDB ObjectId.

I think it's somewhat misleading to say a "JSON-object" to refer to an actual Object, JSON's `object` production defines how to form a UTF string, after all.

Is it possible to write tests for this, that this patch would fix?

**Comment by pdunkel** [comment]
The test is fairly simple:

```javascript
'use strict';

/*jsl predef:define*/
/*jsl predef:it*/

var Validator = require('../lib/validator');
var should = require('chai').should();

describe('Arrays', function () {
  describe('cross-context array', function () {
    beforeEach(function () {
      this.validator = new Validator();
    });
    it('should validate an empty array', function () {
      this.validator.validate(true, localSchema());
    });
    it('should validate a cross-context array', function() {
      this.validator.validate(true, contextSchema());
    });
  });
});

function localSchema() {
    return {
        oneOf: [
            { type:'string' },
            { type: 'boolean' }
        ]
    };
}
function contextSchema() {
    var vm = require('vm');
    return vm.runInNewContext([ '(', ')'].join(JSON.stringify(localSchema())));
}
```

**Comment by pdunkel** [comment]
Can you also explain to me the schema you use to validate that an object has a specific prototype? That would be very interesting. Though this quote from the spec made me think that would be hard/impossible:

> 5.2.  Programming language independence
>
> JSON Schema is programming language agnostic. The only limitations are the ones expressed by [RFC4627](http://tools.ietf.org/html/rfc4627) and those of the host programming language.

**Comment by Acubed** [comment]
STRICTLY speaking, this library doesn't validate JSON, which is a text (Unicode) format; it validates javascript objects, which (after discarding whitespace and formatting) can represent a far wider range of values than JSON describes (like Date).

The goal is to get 100% compliance with JSON Schema; but if we can support additional stuff on top of that too, then it's not hurting anything.

That test looks good, do you think you could add it to the PR?

I've also been intending to support a few more array-like types, perhaps we should have a runtime setting that can provide a comparator. (I can take a look at that.)

**Comment by pdunkel** [comment]
I'll add the test to the PR.

**Comment by awwright** [comment]
Most of these issues should be fixed now; please open a new issue if you encounter any.

**Pull request closed without merging**
